# Generated by Django 4.2.3 on 2023-07-04 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userProfile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='default.png', max_length=50, upload_to=userProfile.models.get_file_path)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('question', models.CharField(default='We want to hear more', max_length=500)),
                ('resultsToDisplay', models.PositiveIntegerField(default=5)),
                ('orderBy', models.IntegerField(choices=[(1, '-ratings'), (2, '-created_on'), (3, 'created_on')], default=1)),
                ('instagram_url', models.URLField(blank=True, max_length=300)),
                ('youtube_url', models.URLField(blank=True, max_length=300)),
                ('linkedin_url', models.URLField(blank=True, max_length=300)),
                ('facebook_url', models.URLField(blank=True, max_length=300)),
                ('website_url', models.URLField(blank=True, max_length=300)),
                ('twitter_url', models.URLField(blank=True, max_length=300)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
