# Generated by Django 4.2 on 2023-05-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
