# Generated by Django 4.2.1 on 2023-07-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='question',
            field=models.CharField(blank=True, default='How was the packaging experience?', max_length=500, null=True),
        ),
    ]
