# Generated by Django 4.2 on 2023-04-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='name',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='updated_at',
        ),
    ]
