# Generated by Django 4.2 on 2023-04-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_rename_name_creator_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
