# Generated by Django 4.2 on 2023-04-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_creator_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='question',
            field=models.CharField(default='Give your feedback.', max_length=500),
        ),
    ]
