# Generated by Django 4.2.1 on 2023-08-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_alter_creator_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='question',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
