# Generated by Django 4.2 on 2023-04-26 20:16

from django.db import migrations, models
import django.db.models.deletion
import reviewService.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userProfile', '0004_creator_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(max_length=300, null=True, upload_to=reviewService.models.get_file_path)),
                ('answer', models.CharField(max_length=1500, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.creator')),
            ],
        ),
    ]
