# Generated by Django 4.2.2 on 2023-06-17 18:10

from django.db import migrations, models
import django.db.models.deletion
import reviewService.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewee', models.CharField(blank=True, default='Anonymous', max_length=200)),
                ('ratings', models.PositiveSmallIntegerField()),
                ('packaging', models.TextField(blank=True, max_length=1500, null=True)),
                ('feedback', models.CharField(blank=True, max_length=1500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.creator')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(max_length=50, null=True, upload_to=reviewService.models.get_file_path)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewService.review')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
