# Generated by Django 4.2 on 2023-04-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewService', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='image',
            new_name='attachments',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='answer',
            new_name='feedback',
        ),
    ]
