# Generated by Django 4.2 on 2023-05-01 08:07

from django.db import migrations, models
import django.db.models.deletion
import reviewService.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewService', '0002_rename_image_review_attachments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='attachments',
        ),
        migrations.CreateModel(
            name='ReviewImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments', models.ImageField(max_length=300, null=True, upload_to=reviewService.models.get_file_path)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewService.review')),
            ],
        ),
    ]
