# Generated by Django 4.2 on 2023-04-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewService', '0003_remove_review_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='packaging',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewe',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
