# Generated by Django 4.2 on 2023-04-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewService', '0004_review_packaging_review_reviewe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewe',
            new_name='reviewee',
        ),
    ]
