# Generated by Django 4.2 on 2023-04-30 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewService', '0005_rename_reviewe_review_reviewee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ratings',
        ),
    ]
