# Generated by Django 4.2 on 2023-04-30 17:02

from django.db import migrations, models
import reviewService.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewService', '0006_remove_review_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='attachments',
            field=models.FileField(max_length=300, null=True, upload_to=reviewService.models.get_file_path),
        ),
    ]
